
import "wtypes.idl";
import "XLoper.idl";

[
  uuid(05FE15B4-AB13-4064-A22A-1A816059B6A0),
  version(1.0)
]
library LibXLLServer
{
	importlib("stdole32.tlb");
	importlib("stdole.tlb"); 

	[uuid(05FE15B4-AB13-4064-A22A-1A816059B6A1)]
	interface IXLLCallback : IUnknown
	{
		[id(1)] HRESULT Execute([in] SAFEARRAY(wireXLOPER) args, [out, retval] wireXLOPER* result);
	};	
	
	[uuid(05FE15B4-AB13-4064-A22A-1A816059B6A2)]
	interface IXLLServer : IUnknown
	{
		[id(1)] HRESULT Startup([in] IXLLCallback* callback, [out, retval] int* result);
		[id(2)] HRESULT GetFunctionCount([out, retval] int* count);
		[id(3)] HRESULT GetFunction([in] int index, [out, retval] SAFEARRAY(BSTR) info);
		[id(4)] HRESULT GetCommandCount([out, retval] int* count);
		[id(5)] HRESULT GetCommand([in] int index, [out, retval] SAFEARRAY(BSTR) info);
		[id(6)] HRESULT ExecuteFunction([in] int index, [in] SAFEARRAY(wireXLOPER) args, [out, retval] wireXLOPER* result);
		[id(7)] HRESULT ExecuteCommand([in] int index, [in] SAFEARRAY(wireXLOPER) args, [out, retval] wireXLOPER* result);
		[id(8)] HRESULT Shutdown([out, retval] int* result);
	}

	[uuid(05FE15B4-AB13-4064-A22A-1A816059B6A3)]
	coclass XLLServer
	{
		[default] interface IXLLServer;
	}
}